sudo: false
language: node_js
node_js:
  - "16"
  - "14"
  - "12"
matrix:
  fast_finish: true

jobs:
  include:
    - stage: audit
      name: audit
      script: npm run better-audit --prod
    - stage: test
      name: test
      script: npm test
